project:
  type: website
  output-dir: docs

website:
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Dataset"
        href: dataset.qmd
      - text: "Annotation Guidelines"
        href: guidelines.qmd
      - text: "Pipeline"
        href: pipeline.qmd
      - text: "Evaluation"
        href: evaluation.qmd
      - text: "Publications"
        href: publications.pdf
      - text: "Team"
        href: team.qmd
    right:
      - text: "Impressum"
        href: impressum.qmd
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    lightbox: true
    include-after-body: lightbox-history.html